---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/ci/tasks/load-tests.sh
