---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/ci/tasks/update-routes.sh
